language: android
script: "./gradlew build"
android:
  components:
    - tools
    - platforms-tools
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-android-support
    - android-22
    - android-29
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
